version: '3.7'
services:
    mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - 3306:3306

    webserver:
      image: nginx:alpine
      working_dir: /var/www/
      volumes:
          - .:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      environment:
        APP_ENV: dev
      depends_on:
        - php-fpm

    php-fpm:
      image: piotrpoloczek/sym4-php:v1
      working_dir: /var/www/
      build: ./docker/php-fpm
      volumes:
        - .:/var/www
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      environment:
        APP_ENV: dev
      depends_on:
        - mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8080:80
