<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9ngAOF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9ngAOF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF9ngAOF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF9ngAOF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF9ngAOF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F9ngAOF',
    'container.build_id' => '46e4bf95',
    'container.build_time' => 1564779354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9ngAOF');
